### ISSUE TITLE
在使用kiwi --translate之后不能成功翻译

### ISSUE THREAD

**Issue by huchaolin** [alibaba/kiwi#114]
如下报错信息所示，该如何解决呢， 文档实在太简洁了，不知道从何入手；
我看了下en-US文件夹有对应的映射文件， 但是映射出来的是中文的， 我只是在kiwi --init 的时候配置了文件目录，没有用默认的，然后kiwi -- extract 之后 执行 kiwi --translate 就报错了

最开始报错 是 `⠋ 使用 Baidu 翻译中...(node:27871) UnhandledPromiseRejectionWarning: Error: Cannot find module './common'`
再次执行 kiwi --translate 如下报错
`> kiwi --translate

⠦ 使用 Baidu 翻译中...en-US 自动翻译完成
/..../node_modules/kiwi-clis/dist/import.js:27
            throw new Error(`Illegal message: ${value}`);
            ^

Error: Illegal message: Add "and" condition
    at /.../node_modules/kiwi-clis/src/import.ts:26:13
    at Object.parseRows [as tsvParseRows] (/.../node_modules/d3-dsv/dist/d3-dsv.js:122:23)
    at getMessagesToImport (/.../node_modules/kiwi-clis/src/import.ts:20:20)
    at Object.importMessages (/.../node_modules/kiwi-clis/src/import.ts:59:26)
    at /.../node_modules/kiwi-clis/src/translate.ts:158:9
    at /.../node_modules/graceful-fs/graceful-fs.js:61:14
    at FSReqCallback.oncomplete (fs.js:179:23)
`

这是我的config.json配置 `
{
  "kiwiDir": "./i18n/lang",
  "srcLang": "zh-CN",
  "distLangs": [
    "en-US"
  ],
  "googleApiKey": "",
  "baiduApiKey": {
    "appId": "xxxxx",
    "appKey": "xxxxx"
  },
  "baiduLangMap": {
    "en-US": "en"
  },
  "translateOptions": {
    "concurrentLimit": 10,
    "requestOptions": {}
  },
  "defaultTranslateKeyApi": "Pinyin",
  "importI18N": "import I18N from '@i18n';",
  "ignoreDir": ["./src/assets", "./src/server", "./src/mock", "./src/common", "./src/utils", "./node_modules"],
  "ignoreFile": ""
}
`

**Comment by dinglino1** [comment]
![image](https://user-images.githubusercontent.com/25605948/202906352-d045e6e6-b449-4e2e-879c-c86964e424a6.png)
我也出现类似的问题，其他语种没问题，就这个西班牙翻译就报错。

**Comment by heyangxing** [comment]
写一个正则判断
是双引号包裹
