### ISSUE TITLE
执行“kiwi --export”提示“Cannot find name 'exports'”

### ISSUE THREAD

**Issue by crisLotus** [alibaba/kiwi#62]
执行“kiwi --export”提示以下报错，请问是哪里出问题了，可以给一点提示吗？万分感谢！
`
TSError: ⨯ Unable to compile TypeScript:
.kiwi/zh-CN/ChannelHeader.ts(2,23): error TS2304: Cannot find name \'exports\'.
.kiwi/zh-CN/ChannelHeader.ts(3,1): error TS2304: Cannot find name 'exports'.
    at createTSError (C:\Users\Administrator\AppData\Local\Yarn\Data\global\node_modules\ts-node\src\index.ts:261:12)
    at getOutput (C:\Users\Administrator\AppData\Local\Yarn\Data\global\node_modules\ts-node\src\index.ts:367:40)
    at Object.compile (C:\Users\Administrator\AppData\Local\Yarn\Data\global\node_modules\ts-node\src\index.ts:558:11)
    at Module.m._compile (C:\Users\Administrator\AppData\Local\Yarn\Data\global\node_modules\ts-node\src\index.ts:439:43)
    at Module.m._compile (C:\Users\Administrator\AppData\Local\Yarn\Data\global\node_modules\ts-node\src\index.ts:439:23)
    at Module._extensions..js (module.js:663:10)`

**Comment by Doubledream** [comment]
kiwi --export [filePath] en-US

**Comment by zongwenjian** [comment]
[Cannot find name 'exports'](https://github.com/alibaba/kiwi/issues/84)

**Comment by zongwenjian** [comment]
#84
